
#General Configuration
[General]
	#if set to true no modspecific mobs will attack, overrides the canAttack of every mob
	AmbientMode = false
	#wether or not bananas should drop
	DoBananaDrops = true
	#chance in % for each block to drop a banana
	#Range: 0.0 ~ 100.0
	BananaDropChance = 45.0

#Mob-Config for Elephant
[Elephant]
	CanAttack = true
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	Health = 60.0
	#requires Client and Server restart | be careful, even small changes can have a high impact
	#Range: 0.05 ~ 10.0
	MovementSpeed = 0.25
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	AttackDamage = 7.0
	#requires Client and Server restart
	#Range: 1 ~ 15
	MaxSpawnedInChunk = 5

#Mob-Config for Giraffe
[Giraffe]
	CanAttack = true
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	Health = 30.0
	#requires Client and Server restart | be careful, even small changes can have a high impact
	#Range: 0.05 ~ 10.0
	MovementSpeed = 0.3
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	AttackDamage = 4.0
	#requires Client and Server restart
	#Range: 1 ~ 15
	MaxSpawnedInChunk = 5

	#the values are considered as weighted-random
	[Giraffe.ColorVariantWeights]
		Color1Weight = 50
		Color2Weight = 50
		AlbinoWeight = 1

#Mob-Config for Lion
[Lion]
	CanAttack = true
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	Health = 20.0
	#requires Client and Server restart | be careful, even small changes can have a high impact
	#Range: 0.05 ~ 10.0
	MovementSpeed = 0.33
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	AttackDamage = 5.0
	#requires Client and Server restart
	#Range: 1 ~ 15
	MaxSpawnedInChunk = 4

	#the values are considered as weighted-random
	[Lion.GenderWeights]
		GenderMaleWeight = 50
		GenderFemaleWeight = 50

	#the values are considered as weighted-random
	[Lion.ColorVariantWeights]
		Color1Weight = 99
		AlbinoWeight = 1

#Mob-Config for Shark
[Shark]
	CanAttack = true
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	Health = 22.0
	#requires Client and Server restart | be careful, even small changes can have a high impact
	#Range: 0.05 ~ 10.0
	MovementSpeed = 1.05
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	AttackDamage = 6.0
	#requires Client and Server restart
	#Range: 1 ~ 15
	MaxSpawnedInChunk = 3

#Mob-Config for Penguin
[Penguin]
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	Health = 10.0
	#requires Client and Server restart | be careful, even small changes can have a high impact
	#Range: 0.05 ~ 10.0
	MovementSpeed = 0.25
	#requires Client and Server restart
	#Range: 1 ~ 15
	MaxSpawnedInChunk = 6

#Mob-Config for Flamingo
[Flamingo]
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	Health = 10.0
	#requires Client and Server restart | be careful, even small changes can have a high impact
	#Range: 0.05 ~ 10.0
	MovementSpeed = 0.25
	#requires Client and Server restart
	#Range: 1 ~ 15
	MaxSpawnedInChunk = 6

#Mob-Config for Ostrich
[Ostrich]
	CanBeRidden = true
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	Health = 20.0
	#requires Client and Server restart | be careful, even small changes can have a high impact
	#Range: 0.05 ~ 10.0
	MovementSpeed = 0.25
	#requires Client and Server restart
	#Range: 1 ~ 15
	MaxSpawnedInChunk = 5

#Mob-Config for Crab
[Crab]
	CanAttack = true
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	Health = 8.0
	#requires Client and Server restart | be careful, even small changes can have a high impact
	#Range: 0.05 ~ 10.0
	MovementSpeed = 0.2
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	AttackDamage = 1.0
	#requires Client and Server restart
	#Range: 1 ~ 15
	MaxSpawnedInChunk = 8

	#the values are considered as weighted-random
	[Crab.ColorVariantWeights]
		Color1Weight = 50
		Color2Weight = 50
		AlbinoWeight = 1

	#the values are considered as weighted-random
	[Crab.ScalingWeights]
		Scaling1Weight = 30
		Scaling2Weight = 30
		Scaling3Weight = 25
		Scaling4Weight = 15

#Mob-Config for Mantaray
[Mantaray]
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	Health = 10.0
	#requires Client and Server restart | be careful, even small changes can have a high impact
	#Range: 0.05 ~ 10.0
	MovementSpeed = 1.0
	#requires Client and Server restart
	#Range: 1 ~ 15
	MaxSpawnedInChunk = 5

	#the values are considered as weighted-random
	[Mantaray.ColorVariantWeights]
		Color1Weight = 50
		Color2Weight = 50

	#the values are considered as weighted-random
	[Mantaray.ScalingWeights]
		Scaling1Weight = 25
		Scaling2Weight = 25
		Scaling3Weight = 25
		Scaling4Weight = 25

#Mob-Config for Raccoon
[Raccoon]
	CanAttack = true
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	Health = 10.0
	#requires Client and Server restart | be careful, even small changes can have a high impact
	#Range: 0.05 ~ 10.0
	MovementSpeed = 0.23
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	AttackDamage = 2.0
	#requires Client and Server restart
	#Range: 1 ~ 15
	MaxSpawnedInChunk = 6

#Mob-Config for Owl
[Owl]
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	Health = 10.0
	#requires Client and Server restart | be careful, even small changes can have a high impact
	#Range: 0.05 ~ 10.0
	MovementSpeed = 0.25
	#requires Client and Server restart | be careful, even small changes can have a high impact
	#Range: 0.05 ~ 10.0
	FlyingSpeed = 0.5
	#requires Client and Server restart
	#Range: 1 ~ 15
	MaxSpawnedInChunk = 6

	#the values are considered as weighted-random
	[Owl.ColorVariantWeights]
		colorBrownWeight = 33
		colorWhiteWeight = 33
		colorBlackWeight = 33

#Mob-Config for AncientBlaze
[AncientBlaze]
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	Health = 250.0
	#requires Client and Server restart | be careful, even small changes can have a high impact
	#Range: 0.05 ~ 10.0
	MovementSpeed = 0.25
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	AttackDamage = 6.0
	#time in ticks, until the entity can be damaged | requires Client and Server restart
	#Range: 10 ~ 32767
	InvulnerableTime = 200
	#amount of blazes spawned on death | requires Client and Server restart
	#Range: 0 ~ 16
	BlazeSpawnCount = 4
	#max amount of large fireballs to shoot | requires Client and Server restart
	#Range: 0 ~ 10
	LargeFireballCount = 6
	#chance for the attack to be a large fireball | requires Client and Server restart
	#Range: 0 ~ 100
	LargeFireballChance = 20
	CanAttack = true
	#wether or not the entity shall despawn when peaceful is turned on
	PeacefulDespawn = true
	#wether or not the entity shall spawn when conditions are met
	CanSpawn = true

#Mob-Config for Koala
[Koala]
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	Health = 10.0
	#requires Client and Server restart | be careful, even small changes can have a high impact
	#Range: 0.05 ~ 10.0
	MovementSpeed = 0.17
	#requires Client and Server restart
	#Range: 1 ~ 15
	MaxSpawnedInChunk = 5

#Mob-Config for Snail
[Snail]
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	Health = 4.0
	#requires Client and Server restart | be careful, even small changes can have a high impact
	#Range: 0.05 ~ 10.0
	MovementSpeed = 0.1
	#requires Client and Server restart
	#Range: 1 ~ 15
	MaxSpawnedInChunk = 6

#Mob-Config for Monkey
[Monkey]
	CanAttack = true
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	Health = 6.0
	#requires Client and Server restart | be careful, even small changes can have a high impact
	#Range: 0.05 ~ 10.0
	MovementSpeed = 0.23
	#requires Client and Server restart
	#Range: 1.0 ~ 32767.0
	AttackDamage = 3.0
	#requires Client and Server restart
	#Range: 1 ~ 15
	MaxSpawnedInChunk = 7

