
#General settings
[general]
	#Indicates how much liquid each Tank Block can hold
	#Range: 1000 ~ 300000
	capacity = 160000
	#Indicates the maximum size of each Tank
	#Range: 10 ~ 400
	modules = 300
	#If set to true, it will not be possible to have infinite water source
	enabled = false

