
#General Settings
[general]
	#Forge Energy conversion rate (in FE/t at max RPM).
	#Range: > 0
	fe_conversion = 60
	#Baseline stress factor for the Alternator and Electric Motor.
	#Range: > 0
	generator_stress = 4096

#Electric Motor
[electric_motor]
	#Electric Motor max input in FE (Energy transfer not consumption).
	#Range: > 0
	motor_max_input = 8192
	#Electric Motor internal capacity in FE.
	#Range: > 0
	motor_capacity = 16000
	#Electric Motor min/max RPM.
	#Range: 1 ~ 256
	motor_rpm_range = 256
	#Electric Motor minimum required energy consumption in FE/t.
	#Range: > 0
	motor_min_consumption = 10

#Alternator
[alternator]
	#Alternator max input in FE (Energy transfer not generation).
	#Range: > 0
	generator_max_output = 8192
	#Alternator internal capacity in FE.
	#Range: > 0
	generator_capacity = 32000
	#Alternator efficiency relative to base conversion rate.
	#Range: 0.01 ~ 1.0
	generator_efficiency = 0.75

#Rolling Mill
[rolling_mill]
	#Rolling Mill duration in ticks.
	#Range: > 0
	rolling_mill_processing_duration = 100
	#Rolling Mill base stress impact.
	#Range: 0 ~ 1024
	rolling_mill_stress = 16

#Heater
[heater]
	#Induction Heater max input in FE (Energy transfer not consumption).
	#Range: > 0
	heater_max_input = 8192
	#Induction Heater internal capacity in FE.
	#Range: > 0
	heater_capacity = 16000
	#Induction Heater normal consumption rate in FE/t.
	#Range: > 0
	heater_normal_consumption = 30
	#Induction Heater when attached to a Furnace Engine consumption rate in FE/t.
	#Range: > 0
	heater_furnace_engine_consumption = 400
	#Enable Induction Heater when attached to a Furnace Engine.
	heater_furnace_engine_enable = false

#Wires
[wires]
	#Connector max input (Energy transfer).
	#Range: > 0
	connector_max_input = 2048
	#Connector max output (Energy transfer).
	#Range: > 0
	connector_max_output = 2048
	#Connector internal capacity.
	#Range: > 0
	connector_capacity = 8196
	#Loss per block in copper wire (Not implemented, currently no loss).
	#Range: 0.0 ~ 0.5
	copper_wire_loss = 0.02
	#Loss per block in gold wire (Not implemented, currently no loss).
	#Range: 0.0 ~ 0.5
	gold_wire_loss = 0.005

#Accumulator
[accumulator]
	#Accumulator max input (Energy transfer).
	#Range: > 0
	accumulator_max_input = 8192
	#Accumulator max output (Energy transfer).
	#Range: > 0
	accumulator_max_output = 8192
	#Accumulator internal capacity.
	#Range: > 0
	accumulator_capacity = 4196000

#Misc
[misc]
	#Diamond Grit Sandpaper durability (number of uses).
	#Range: > 3
	diamond_grit_sandpaper_uses = 1024

