
#Server and Client side changes.
[common]
	#Obsidian Spire rarity (higher number = lower spawnrate)
	obsidianSpireSpawnRate = 16
	#Disables the Looter's ability to take the player's weapon (This makes them spawn with a random weapon, good and bad)
	disableLooterStealing = true
	#Farlander Loot Well rarity (higher number = lower spawnrate)
	farlanderLootWellSpawnRate = 20

	[common.small_house]
		#Spacing between structures
		#Range: > 1
		spacing = 25
		#Offsets the spacing of the structures randomly
		#Range: > 0
		offset = 5
		#Chance of generating in an allowed chunk
		#Range: 0.0 ~ 1.0
		probability = 0.6

	[common.farlander_village]
		#Spacing between structures
		#Range: > 1
		spacing = 40
		#Offsets the spacing of the structures randomly
		#Range: > 0
		offset = 15
		#Chance of generating in an allowed chunk
		#Range: 0.0 ~ 1.0
		probability = 0.3

