
[structures]
	#Structure Generation Config
	#Take care what you change, this changes may cant be undone
	#
	#Biomes in which Structures cant generate in
	blacklisted_biomes = ["minecraft:ocean", "minecraft:river", "minecraft:nether_wastes", "minecraft:the_end", "minecraft:frozen_ocean", "minecraft:frozen_river", "minecraft:deep_ocean", "minecraft:small_end_islands", "minecraft:end_midlands", "minecraft:end_highlands", "minecraft:end_barrens", "minecraft:warm_ocean", "minecraft:lukewarm_ocean", "minecraft:cold_ocean", "minecraft:deep_warm_ocean", "minecraft:deep_lukewarm_ocean", "minecraft:deep_cold_ocean", "minecraft:deep_frozen_ocean", "minecraft:soul_sand_valley", "minecraft:crimson_forest", "minecraft:warped_forest", "minecraft:basalt_deltas"]

	[structures.small_tempel]
		#Small Tempel Distance (in chunks) [default: 75]
		#Range: 1 ~ 500
		distance = 75
		#Small Tempel Seed (Only Change if you know what you are doing)[default: 4765321]
		#Range: > -2147483648
		seed = 4765321
		#Small Tempel Minimum Separation (in chunks) [default: 13]
		#Range: 1 ~ 500
		separation = 13
		#Biomes the Small Tempel can NOT generate in
		biome_blacklist = []
		#Generate Small Tempels?
		generate = true
		#Biome Types the Small Tempel can generate in
		biome_categories = ["PLAINS", "FOREST", "TAIGA"]
		#Small Tempel Spawn Chance [default: 0.6]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.6

	[structures.player_house]
		#Player House Distance (in chunks) [default: 80]
		#Range: 1 ~ 500
		distance = 80
		#Player House Seed (Only Change if you know what you are doing)[default: 751963298]
		#Range: > -2147483648
		seed = 751963298
		#Player House Minimum Separation (in chunks) [default: 15]
		#Range: 1 ~ 500
		separation = 15
		#Player House Generate Loot Chance [default: 1.0]
		#Range: 0.0 ~ 1.0
		loot_chance = 1.0
		#Biomes the Player House can NOT generate in
		biome_blacklist = []
		#Generate Player Houses?
		generate = true
		#Biome Types the Player House can generate in
		biome_categories = ["PLAINS", "FOREST", "TAIGA"]
		#Player House Spawn Chance [default: 0.6]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.4

	[structures.nether_shrine]
		#Nether Shrine Distance (in chunks) [default: 80]
		#Range: 1 ~ 500
		distance = 80
		#Nether Shrine Seed (Only Change if you know what you are doing)[default: 653267]
		#Range: > -2147483648
		seed = 653267
		#Nether Shrine Minimum Separation (in chunks) [default: 15]
		#Range: 1 ~ 500
		separation = 15
		#Nether Shrine Generate Loot Chance [default: 1.0]
		#Range: 0.0 ~ 1.0
		loot_chance = 1.0
		#Biomes the Nether Shrine can NOT generate in
		biome_blacklist = []
		#Generate Nether Shrines?
		generate = true
		#Biome Types the Nether Shrine can generate in
		biome_categories = ["PLAINS", "FOREST", "TAIGA"]
		#Nether Shrine Spawn Chance [default: 0.6]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.6

	[structures.high_tempel]
		#High Tempel Distance (in chunks) [default: 85]
		#Range: 1 ~ 500
		distance = 85
		#High Tempel Seed (Only Change if you know what you are doing)[default: 536987987]
		#Range: > -2147483648
		seed = 536987987
		#High Tempel Minimum Separation (in chunks) [default: 18]
		#Range: 1 ~ 500
		separation = 18
		#Biomes the High Tempel can NOT generate in
		biome_blacklist = []
		#Generate High Tempels?
		generate = true
		#Biome Types the High Tempel can generate in
		biome_categories = ["PLAINS", "FOREST", "TAIGA"]
		#High Tempel Spawn Chance [default: 0.6]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.6

	[structures.nether_pyramid]
		#Nether Pyramid Distance (in chunks) [default: 150]
		#Range: 1 ~ 500
		distance = 150
		#Nether Pyramid Seed (Only Change if you know what you are doing)[default: 7428394]
		#Range: > -2147483648
		seed = 7428394
		#Nether Pyramid Minimum Separation (in chunks) [default: 50]
		#Range: 1 ~ 500
		separation = 50
		#Nether Pyramid Generate Loot Chance [default: 1.0]
		#Range: 0.0 ~ 1.0
		loot_chance = 1.0
		#Biomes the Nether Pyramid can NOT generate in
		biome_blacklist = []
		#Generate Nether Pyramids?
		generate = true
		#Biome Types the Nether Pyramid can generate in
		biome_categories = ["PLAINS", "FOREST", "TAIGA"]
		#Nether Pyramid Spawn Chance [default: 0.6]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.1

	[structures.ballon]
		#Ballon Distance (in chunks) [default: 80]
		#Range: 1 ~ 500
		distance = 80
		#Ballon Seed (Only Change if you know what you are doing)[default: 143665]
		#Range: > -2147483648
		seed = 143665
		#Ballon Minimum Separation (in chunks) [default: 15]
		#Range: 1 ~ 500
		separation = 15
		#Biomes the Ballon can NOT generate in
		biome_blacklist = []
		#Generate Ballons?
		generate = true
		#Biome Types the Ballon can generate in
		biome_categories = ["PLAINS", "FOREST", "TAIGA"]
		#Ballon Spawn Chance [default: 0.6]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.6

	[structures.bees]
		#Bees Distance (in chunks) [default: 70]
		#Range: 1 ~ 500
		distance = 70
		#Bees Seed (Only Change if you know what you are doing)[default: 779806245]
		#Range: > -2147483648
		seed = 779806245
		#Bees Minimum Separation (in chunks) [default: 12]
		#Range: 1 ~ 500
		separation = 12
		#Biomes the Bees can NOT generate in
		biome_blacklist = []
		#Generate Beess?
		generate = true
		#Biome Types the Bees can generate in
		biome_categories = ["PLAINS", "FOREST", "TAIGA"]
		#Bees Spawn Chance [default: 0.6]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.6

	[structures.water_shrine]
		#Water Shrine Distance (in chunks) [default: 80]
		#Range: 1 ~ 500
		distance = 80
		#Water Shrine Seed (Only Change if you know what you are doing)[default: 143665]
		#Range: > -2147483648
		seed = 1520586
		#Water Shrine Minimum Separation (in chunks) [default: 15]
		#Range: 1 ~ 500
		separation = 15
		#Biomes the Water Shrine can NOT generate in
		biome_blacklist = []
		#Generate Water Shrines?
		generate = true
		#Biome Types the Water Shrine can generate in
		biome_categories = ["PLAINS", "FOREST", "TAIGA"]
		#Water Shrine Spawn Chance [default: 0.6]
		#Range: 0.0 ~ 1.0
		spawn_chance = 0.6

